# Dev Environment — am-auth-tokens
environment: dev
replicaCount: 1

global:
  vault:
    secrets:
      auth: "apps/data/dev/services/am-auth"
      infra: "apps/data/dev/infra/postgres"
      redis: "apps/data/dev/infra/redis"
    templates:
      infra: |
        {{- with secret "apps/data/dev/infra/postgres" -}}
        export DATABASE_URL="{{ .Data.data.url }}"
        {{- end }}
      redis: |
        {{- with secret "apps/data/dev/infra/redis" -}}
        export REDIS_HOST="{{ .Data.data.host }}"
        export REDIS_PORT="{{ .Data.data.port }}"
        export REDIS_PASSWORD="{{ .Data.data.password }}"
        export REDIS_URL="{{ .Data.data.url }}"
        {{- end }}

env:
  LOG_LEVEL: "DEBUG"
  API_V1_STR: "/auth/v1"
  DEBUG: "true"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: am-apps-dev-dev-global-cors@kubernetescrd
  hosts:
    - host: am-dev.asrax.in
      paths:
        - path: /auth
          pathType: Prefix
