environment: preprod
replicaCount: 1

global:
  vault:
    secrets:
      jwt:      "secret/data/preprod/apps/security"
      postgres: "secret/data/preprod/apps/database"
      redis:    "secret/data/preprod/apps/database"
      config:   "secret/data/preprod/apps/config"
