vault:
  secretPaths:
    auth:
      mappings:
        ALLOWED_ORIGINS: "ALLOWED_ORIGINS"
        SECRET_KEY: "SECRET_KEY"
        JWT_SECRET: "JWT_SECRET"
        SMTP_HOST: "SMTP_HOST"
        SMTP_PORT: "SMTP_PORT"
    postgres:
      mappings:
        DATABASE_URL: "url"
